//
//  CreateToDoInteractor.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateToDoBusinessLogic {
  func createToDo(request: CreateToDo.CreateToDo.Request)
}

protocol CreateToDoDataStore {
  
}

class CreateToDoInteractor: CreateToDoBusinessLogic, CreateToDoDataStore {
  var presenter: CreateToDoPresentationLogic?
  var worker: CreateToDoWorkerLogic?
  
  func createToDo(request: CreateToDo.CreateToDo.Request) {
    worker?.createToDo(request.todo) { error, todo in
      let response = CreateToDo.CreateToDo.Response(error: error)
      self.presenter?.createToDo(response: response)
    }
  }
}
