//
//  CreateToDoInteractor.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateToDoBusinessLogic
{
  func doSomething(request: CreateToDo.Something.Request)
}

protocol CreateToDoDataStore
{
  //var name: String { get set }
}

class CreateToDoInteractor: CreateToDoBusinessLogic, CreateToDoDataStore
{
  var presenter: CreateToDoPresentationLogic?
  var worker: CreateToDoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateToDo.Something.Request)
  {
    worker = CreateToDoWorker()
    worker?.doSomeWork()
    
    let response = CreateToDo.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
