//
//  CreateToDoModels.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateToDo {
  enum CreateToDo {
    struct Request {
      var todo: ToDo
    }
    
    struct Response {
      var error: ToDosCoreDataManagerError?
    }
    
    struct ViewModel {
      var error: ToDosCoreDataManagerError?
    }
  }
}
