//
//  CreateToDoRouter.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateToDoRoutingLogic {
  func routeToList()
}

protocol CreateToDoDataPassing {
  var dataStore: CreateToDoDataStore? { get }
}

class CreateToDoRouter: NSObject, CreateToDoRoutingLogic, CreateToDoDataPassing {
  weak var viewController: CreateToDoViewController?
  var dataStore: CreateToDoDataStore?
  
  func routeToList() {
    guard let viewController = viewController else {
      fatalError("Must set up VIP components.")
    }

    viewController.dismiss(animated: true)
  }
}
