//
//  CreateToDoPresenter.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateToDoPresentationLogic {
  func createToDo(response: CreateToDo.CreateToDo.Response)
}

class CreateToDoPresenter: CreateToDoPresentationLogic {
  weak var viewController: CreateToDoDisplayLogic?
  
  func createToDo(response: CreateToDo.CreateToDo.Response) {
    let viewModel = CreateToDo.CreateToDo.ViewModel(error: response.error)
    viewController?.createToDo(viewModel: viewModel)
  }
}
