//
//  CreateToDoViewController.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateToDoDisplayLogic: AnyObject {
  func createToDo(viewModel: CreateToDo.CreateToDo.ViewModel)
}

class CreateToDoViewController: UIViewController {
  lazy var createButton: UIButton = {
    let button = UIButton()
    button.addTarget(self, action: #selector(didTapCreateButton), for: .touchUpInside)
    button.setImage(UIImage(systemName: "trash.fill"), for: .normal)
    button.translatesAutoresizingMaskIntoConstraints = false
    return button
  }()
  
  var interactor: CreateToDoBusinessLogic?
  var router: (NSObjectProtocol & CreateToDoRoutingLogic & CreateToDoDataPassing)?
  
  init() {
    super.init(nibName: nil, bundle: nil)
    setup()
  }
  
  required init(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented.")
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  private func setup() {
    let interactor = CreateToDoInteractor()
    let presenter = CreateToDoPresenter()
    let router = CreateToDoRouter()
    let worker = CreateToDoWorker()
    
    let viewController = self
    viewController.interactor = interactor
    viewController.router = router
    
    router.viewController = viewController
    router.dataStore = interactor
    
    interactor.presenter = presenter
    interactor.worker = worker
    
    presenter.viewController = viewController
  }
  
  private func createToDo() {
    
  }
}


// MARK: - CreateToDoDisplayLogic

extension CreateToDoViewController: CreateToDoDisplayLogic {
  func createToDo(viewModel: CreateToDo.CreateToDo.ViewModel) {
    if let error = viewModel.error {
      AlertFactory.show(
        title: "Create Error",
        message: error.description,
        viewController: self
      )
    } else {
      router?.routeToList()
    }
  }
}


// MARK: - Selector

extension CreateToDoViewController {
  @objc private func didTapCreateButton() {
    
  }
}
