//
//  DetailToDoModels.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailToDo
{
  enum Delete {
    struct Request {
      var id: Int16
    }
    
    struct Response {
      var completion: ErrorCompletion
    }
    
    struct ViewModel {
      var isDelete: Bool
    }
  }
  
  enum Update {
    struct Request {
      var todo: ToDo
    }
    
    struct Response {
      var completion: UpdateCompletion
    }
    
    struct ViewModel {
      var todo: ToDo?
    }
  }
}
