//
//  DetailToDoInteractor.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailToDoBusinessLogic
{
  func doSomething(request: DetailToDo.Something.Request)
}

protocol DetailToDoDataStore
{
  //var name: String { get set }
}

class DetailToDoInteractor: DetailToDoBusinessLogic, DetailToDoDataStore
{
  var presenter: DetailToDoPresentationLogic?
  var worker: DetailToDoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailToDo.Something.Request)
  {
    worker = DetailToDoWorker()
    worker?.doSomeWork()
    
    let response = DetailToDo.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
