//
//  DetailToDoWorker.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailToDoWorkerLogic {
  func deleteToDo(id: Int16, completion: @escaping ErrorCompletion)
  func updateToDo(todo: ToDo, completion: @escaping UpdateCompletion)
}

class DetailToDoWorker: DetailToDoWorkerLogic {
  private var manager: ToDosCoreDataManager
  
  init() {
    manager = ToDosCoreDataManager(type: .persistent)
  }
  
  func deleteToDo(id: Int16, completion: @escaping ErrorCompletion) {
    manager.deleteToDo(id: id) { error in
      completion(error)
    }
  }
  
  func updateToDo(todo: ToDo, completion: @escaping UpdateCompletion) {
    manager.updateToDo(todo) { error, todo in
      completion(error, todo)
    }
  }
}
