//
//  DetailToDoPresenter.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailToDoPresentationLogic
{
  func presentSomething(response: DetailToDo.Something.Response)
}

class DetailToDoPresenter: DetailToDoPresentationLogic
{
  weak var viewController: DetailToDoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DetailToDo.Something.Response)
  {
    let viewModel = DetailToDo.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
