//
//  ListToDosRouter.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListToDosRoutingLogic {
  func routeToDetail()
}

protocol ListToDosDataPassing {
  var dataStore: ListToDosDataStore? { get }
}

class ListToDosRouter: NSObject, ListToDosRoutingLogic, ListToDosDataPassing {
  weak var viewController: ListToDosViewController?
  var dataStore: ListToDosDataStore?
  
  func routeToDetail() {
    let destinationViewController = DetailToDoViewController()
    
    guard var destinationDataStore = destinationViewController.router?.dataStore,
          let viewController = viewController,
          let dataStore = dataStore else {
      fatalError("Must set up VIP components.")
    }
    
    passDataToDetail(source: dataStore, destination: &destinationDataStore)
    navigateToDetail(source: viewController, destination: destinationViewController)
  }
  
  func passDataToDetail(source: ListToDosDataStore, destination: inout DetailToDoDataStore) {
    let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
    let selectedToDo = source.todos?[selectedRow!]
    destination.todo = selectedToDo
  }
  
  func navigateToDetail(source: ListToDosViewController, destination: DetailToDoViewController) {
    source.show(destination, sender: nil)
  }
}
