//
//  ListToDosWorker.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListToDosWorkerLogic {
  func requestToDos(date: Date, completion: @escaping FetchToDosCompletion)
}

class ListToDosWorker: ListToDosWorkerLogic {
  private var manager: ToDosCoreDataManager
  
  init() {
    manager = ToDosCoreDataManager(type: .persistent)
  }
  
  func requestToDos(date: Date, completion: @escaping FetchToDosCompletion) {
    manager.fetchToDos(date: date) { todos in
      completion(todos)
    }
  }
}
