//
//  ListToDosPresenter.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListToDosPresentationLogic {
  func presentToDos(response: ListToDos.GetToDos.Response)
}

class ListToDosPresenter: ListToDosPresentationLogic {
  weak var viewController: ListToDosDisplayLogic?
  
  func presentToDos(response: ListToDos.GetToDos.Response) {
    let viewModel = ListToDos.GetToDos.ViewModel(todos: response.todos)
    viewController?.displayToDos(viewModel: viewModel)
  }
}
