//
//  ListToDosInteractor.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListToDosBusinessLogic {
  func requestToDos(request: ListToDos.GetToDos.Request)
}

protocol ListToDosDataStore {
  var todos: [ToDo]? { get set }
}

class ListToDosInteractor: ListToDosBusinessLogic, ListToDosDataStore {
  var presenter: ListToDosPresentationLogic?
  var worker: ListToDosWorkerLogic?
  var todos: [ToDo]?
  
  func requestToDos(request: ListToDos.GetToDos.Request) {
    worker?.requestToDos(date: request.date) { todos in
      let response = ListToDos.GetToDos.Response(todos: todos)
      self.presenter?.presentToDos(response: response)
      self.todos = todos
    }
  }
}
