//
//  ListToDosInteractor.swift
//  CleanToDo
//
//  Created by 재영 on 2022/02/09.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListToDosBusinessLogic
{
  func doSomething(request: ListToDos.Something.Request)
}

protocol ListToDosDataStore
{
  //var name: String { get set }
}

class ListToDosInteractor: ListToDosBusinessLogic, ListToDosDataStore
{
  var presenter: ListToDosPresentationLogic?
  var worker: ListToDosWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListToDos.Something.Request)
  {
    worker = ListToDosWorker()
    worker?.doSomeWork()
    
    let response = ListToDos.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
